### ISSUE TITLE
updateElementInList

### ISSUE THREAD

**Issue by wasilius** [leonardfischer/zenkit-api-client#1]
Hallo Leonard,

erst mal vielen Dank für die Mühe, dir Du hier gemacht hast. Insgesamt hilft das ein bisschen weiter mit der Zenkit-API, die ich allerdings leider im Allgemeinen etwas arg mühsam finde. Ich benötige gerade insbesondere die Funktion `updateElementInList` – Könntest Du eventuell etwas mehr Informationen zu den erwarteten Daten bei den `parameters` geben? Intuitiv würde man ja etwas wie `[Feldname => Feldwert]` vermuten, aber das haut nicht hin.

Hast Du vor noch einen Wrapper zu ergänzen, über den man dann mit den sprechenden Namen arbeiten kann?

Herzliche Grüße

Sebastian

**Comment by wasilius** [comment]
Das konkrete Problem hat sich erledigt, sorry …

**Comment by leonardfischer** [comment]
Hi Sebastian,

ich habe definitiv noch Interesse am API Client weiter zu arbeiten, leider ist es zeitlich aktuell nicht so einfach. Ich denke es gibt hier generell noch viele Bereiche die ergänzt bzw. fertig gemacht werden müssten. Die API ist leider wirklich ein wenig umständlich zu bedienen 🤔 

Falls du konkrete Verbesserungsvorschläge hast lass es mich wissen 😄 

VG Leo
